services:
  - type: web
    name: senti-app
    env: python
    region: frankfurt
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app

    # This runs BEFORE the new version goes live
    releaseCommand: flask db upgrade

    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: DATABASE_URL
        fromDatabase:
          name: senti-db
          property: connectionString

databases:
  - name: senti-db
    plan: free