services:
  - type: web
    name: senti-app
    env: python
    region: frankfurt   # OR oregon â€“ it doesn't break anything
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app

    # THIS IS THE IMPORTANT PART
    # This runs flask db upgrade on every deploy
    releaseCommand: >
      flask db upgrade

    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: DATABASE_URL
        value: sqlite:///database.db