services:
  - type: web
    name: senti-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    releaseCommand: "flask db upgrade"
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: SECRET_KEY
        generateValue: true